dist: trusty
language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - GUZZLE_VERSION=7.*
  - GUZZLE_VERSION=6.*

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: GUZZLE_VERSION=6.* COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: GUZZLE_VERSION=7.* COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    # only guzzle 6 supports php 7.1
    - php: 7.1
      env: GUZZLE_VERSION=6.*

before_script:
  - travis_retry composer require "guzzlehttp/guzzle:${GUZZLE_VERSION}" --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
