name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
        prefer-lowest: ['']
        include:
          - php: '7.2'
            prefer-lowest: '--prefer-lowest'

    name: PHP ${{ matrix.php }} ${{ matrix.prefer-lowest }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Require guzzle version
        run: composer require "guzzlehttp/guzzle:7.*" --no-update

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress ${{ matrix.prefer-lowest }}

      - name: Run tests
        run: vendor/bin/phpunit
